USE myFictionalBusinessL;
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_LocationID FOREIGN KEY(LocationID) REFERENCES Locations(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(ID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetails
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE OrderDetails
ADD CONSTRAINT FK_InvNumber FOREIGN KEY(InventoryNumber) REFERENCES Inventory(LongboardID)
ON UPDATE CASCADE
GO
