USE [master]
GO
/****** Object:  Database [myFictionalBusinessL]    Script Date: 3/1/2022 10:25:06 PM ******/
CREATE DATABASE [myFictionalBusinessL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'myFictionalBusinessL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\myFictionalBusinessL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'myFictionalBusinessL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\myFictionalBusinessL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [myFictionalBusinessL] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [myFictionalBusinessL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [myFictionalBusinessL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET ARITHABORT OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [myFictionalBusinessL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [myFictionalBusinessL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET  ENABLE_BROKER 
GO
ALTER DATABASE [myFictionalBusinessL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [myFictionalBusinessL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET RECOVERY FULL 
GO
ALTER DATABASE [myFictionalBusinessL] SET  MULTI_USER 
GO
ALTER DATABASE [myFictionalBusinessL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [myFictionalBusinessL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [myFictionalBusinessL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [myFictionalBusinessL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [myFictionalBusinessL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [myFictionalBusinessL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'myFictionalBusinessL', N'ON'
GO
ALTER DATABASE [myFictionalBusinessL] SET QUERY_STORE = OFF
GO
USE [myFictionalBusinessL]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 3/1/2022 10:25:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[ID] [int] NOT NULL,
	[Name] [varchar](20) NOT NULL,
	[LName] [varchar](30) NOT NULL,
	[Zipcode] [varchar](10) NOT NULL,
	[Email] [varchar](30) NULL,
	[CellPh] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Inventory]    Script Date: 3/1/2022 10:25:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inventory](
	[LongboardID] [int] NOT NULL,
	[Design] [varchar](200) NOT NULL,
	[BTypes] [varchar](100) NOT NULL,
	[Flex] [varchar](50) NULL,
	[BLength] [varchar](50) NULL,
	[Wheels] [varchar](50) NULL,
	[Cost] [money] NULL,
	[Price] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[LongboardID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Locations]    Script Date: 3/1/2022 10:25:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Locations](
	[ID] [int] NOT NULL,
	[Name] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetails]    Script Date: 3/1/2022 10:25:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetails](
	[ID] [int] NOT NULL,
	[OrderID] [int] NOT NULL,
	[InventoryNumber] [int] NOT NULL,
	[Quantity] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 3/1/2022 10:25:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[ID] [int] NOT NULL,
	[OrderDate] [datetime] NULL,
	[LocationID] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Zipcode]    Script Date: 3/1/2022 10:25:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Zipcode](
	[Zipcode] [varchar](10) NOT NULL,
	[City] [varchar](30) NOT NULL,
	[State] [varchar](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Zipcode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_Zipcode]    Script Date: 3/1/2022 10:25:06 PM ******/
CREATE NONCLUSTERED INDEX [idx_Zipcode] ON [dbo].[Customers]
(
	[Zipcode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_inyNumber]    Script Date: 3/1/2022 10:25:06 PM ******/
CREATE NONCLUSTERED INDEX [idx_inyNumber] ON [dbo].[OrderDetails]
(
	[InventoryNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_OrderID]    Script Date: 3/1/2022 10:25:06 PM ******/
CREATE NONCLUSTERED INDEX [idx_OrderID] ON [dbo].[OrderDetails]
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_Customer]    Script Date: 3/1/2022 10:25:06 PM ******/
CREATE NONCLUSTERED INDEX [idx_Customer] ON [dbo].[Orders]
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_Location]    Script Date: 3/1/2022 10:25:06 PM ******/
CREATE NONCLUSTERED INDEX [idx_Location] ON [dbo].[Orders]
(
	[LocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Zipcode] FOREIGN KEY([Zipcode])
REFERENCES [dbo].[Zipcode] ([Zipcode])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Zipcode]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_InvNumber] FOREIGN KEY([InventoryNumber])
REFERENCES [dbo].[Inventory] ([LongboardID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_InvNumber]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderID] FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderID]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_CustomerID] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customers] ([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_CustomerID]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_LocationID] FOREIGN KEY([LocationID])
REFERENCES [dbo].[Locations] ([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_LocationID]
GO
USE [master]
GO
ALTER DATABASE [myFictionalBusinessL] SET  READ_WRITE 
GO
